name: Docker Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-login-create-image-push:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCOUNT_SECRET }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/underewarrr/starwars-planet-search .
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/underewarrr/starwars-planet-search:latest
